accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
    path('register/', views.account_register, name='account_register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',
                                                form_class=LoginForm), name='account_login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login/'), name='account_logout'),
]

deepsort/urls.py
from django.urls import path

from . import views

from django.conf.urls.static import static
from django.conf import  settings

app_name = 'deepsort'

urlpatterns = [
    path('', views.test, name='test'),
    path('upload/', views.upload, name='upload'),
    path('check/', views.check, name='check'),
    path('view/', views.view_images, name='view_images'),
    path('modify/', views.modify_images, name='modify_images'),
    path('run/<slug:id>/', views.run, name='run'),
    path('save/', views.save_to_database, name='save')
]

object_tracking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('deepsort/', include('deepsort.urls', namespace='deepsort')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home, name='home'),
    path('move/', views.move, name='move'),
    path('merge/', views.merge, name='merge')
]

templates/partials/_footer.html
<footer class="bg-light text-center text-lg-start">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <a class="text-dark" href="#">Obejct Tracking</a>
  </div>
</footer>

templates/partials/_navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
    aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">Object Tracking</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'deepsort:test' %}">Test</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li>
        <a class="nav-link" href="{% url 'deepsort:test' %}">
          Welcome, {{ user.username }}</a>
      </li>
      <li class="nav-item mr-3">
        <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
          <i class="fas fa-sign-out-alt"></i> Logout
        </a>
        <form action="{% url 'accounts:account_logout' %}" method="POST" id="logout">
          {% csrf_token %}
          <input type="hidden">
        </form>
      </li>
      {% else %}
      <li>
        <a class="nav-link" href="{% url 'accounts:account_register' %}">
          <i class="fas fa-user-plus"></i> Register</a>
      </li>
      <li>
        <a class="nav-link" href="{% url 'accounts:account_login' %}">
          <i class="fas fa-sign-in-alt"></i>
          Login</a>
      </li>
      {% endif %}
  </div>
</nav>

templates/partials/_topbar.html
<section id="top-bar top-background" class="p-3">
    <div class="container">
        <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <i class="fas fa-envelope-open"></i> Object Tacking
        </div>
        </div>
    </div>
</section>