accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
    path('register/', views.account_register, name='account_register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',
                                                form_class=LoginForm), name='account_login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login/'), name='account_logout'),
]

object_tracking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('deepsort/', include('deepsort.urls', namespace='deepsort')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home, name='home'),
    path('move/', views.move, name='move'),
    path('merge/', views.merge, name='merge')
]

templates/pages/detail.html
{% extends 'base.html' %}

{% block title %} | detail {% endblock %}

{% load static %}

{% block content %}

<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Food that we provide</h1>
        <p class="lead text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper magna vel lorem gravida porta. Phasellus convallis a turpis ut.</p>
        <p>
          <a href="{% url 'accounts:account_register' %}" class="btn btn-primary my-2">Register Now</a>
        </p>
      </div>
    </div>
  </section>
  <div class="container">
    <div class="d-grid div-category gap-2 d-md-block justify-content-md-center">
      <button class="btn btn-lg" type="button"
      onclick="displayFoodByCategory('all','{% url 'pages:detail' %}', '{{ csrf_token }}')">All</button>
      {% for category in food_category %}
      <button class="btn btn-lg" id="category-btn{{ forloop.counter }}" type="button"
        onclick="displayFoodByCategory('{{ forloop.counter }}','{% url 'pages:detail' %}', '{{ csrf_token }}')">{{ category.name }}</button>
      {% endfor %}
    </div>
  </div>
  <div class="album py-5 bg-light">
    <div class="container">
      <div id="foodCards" class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for food_each in food %}
        <div class="col p-2">
          <div class="card shadow-sm">
            <img class="card-img-top" src="{{ food_each.image.url }}">
            <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ food_each.name }}</text>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

</main>

<script src="{% static 'js/category.js' %}"></script>
{% endblock %}

templates/pages/home.html
{% extends 'base.html' %}

{% block title %} | home {% endblock %}

{% load static %}

{% block content %}

<body class="text-center">
    <div class="container h-100 p-5 mx-auto flex-column">
        <img class="img-cover" src="{% static 'images/cover.jpg' %}">
      <main role="main" class="inner p-5">
        
        <h1 class="heading">Check Your Sales.</h1>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id urna eget nibh porta tristique..</p>
        <p class="lead">
          <a href="{% url 'accounts:account_register' %}" class="btn btn-lg btn-secondary">Register Now</a>
        </p>
        <p class="text-center p-2">
          <a href="{% url 'pages:move' %}"><u>Move</u></a>
        </p>
      </main>
    </div>
</body>

{% endblock %}

templates/pages/move.html
{% extends 'base.html' %}

{% block title %} | Move {% endblock %}

{% load static %}

{% block content %}

<div class="p-5">
    <a class="h1">Person</a>
    <form action="{% url 'pages:merge' %}" method="POST">
        {% csrf_token %}
        <div class="p-3">
            {% for image in images %}
                <input type="checkbox" name="images" id="{{ forloop.counter }}" value="{{image.folder}}" />
                <label for="{{ forloop.counter }}"><img src="{% static image.file %}" /></label>
            {% endfor %}
        </div>
        <div class="container" style="text-align:center;">
            <div class="row justify-content-center">
                <input type="submit" name="merge" value="merge" class="btn btn-primary btn-lg btn-block col-2">
            </div>
        </div>
    </form>
</div>


{% endblock %}