deepsort/urls.py
from django.urls import path

from . import views

from django.conf.urls.static import static
from django.conf import  settings

app_name = 'deepsort'

urlpatterns = [
    path('', views.test, name='test'),
    path('upload/', views.upload, name='upload'),
    path('check/', views.check, name='check'),
    path('view/', views.view_images, name='view_images'),
    path('modify/', views.modify_images, name='modify_images'),
    path('run/<slug:id>/', views.run, name='run'),
    path('save/', views.save_to_database, name='save')
]

object_tracking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('deepsort/', include('deepsort.urls', namespace='deepsort')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home, name='home'),
    path('move/', views.move, name='move'),
    path('merge/', views.merge, name='merge')
]

deepsort/models.py
from django.urls import reverse
from django.db import models
 

def image_path(instance, filename):
    return 'images/{0}/{1}/{1}_{2}'.format(instance.video.title, instance.person, filename)
 

class Video(models.Model):
    title = models.CharField(max_length=100)
    video = models.FileField(upload_to='videos/%y')
     
    class Meta:
        verbose_name = 'video'
        verbose_name_plural = 'videos'
         
    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("deepsort:run", args=[self.id])


class Image(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    person = models.CharField(max_length=50)
    coordinates = models.CharField(max_length=10)
    file = models.FileField(upload_to=image_path)
    
    class Meta:
        verbose_name = 'image'
        verbose_name_plural = 'images'

deepsort/forms.py
from django import forms

from .models import Videos

class VideoForm(forms.ModelForm):
    class Meta:
        model = Videos
        fields=("title", "video")

deepsort/views.py
from pathlib import Path
from asgiref.sync import async_to_sync
from django.shortcuts import render, redirect



BASE_DIR = str(Path(__file__).resolve().parent.parent)



def test(request):
    return render(request, 'deepsort/test.html')


def upload(request):
    return render(request, 'deepsort/upload.html', {'form': 1})


def modify_images(request):

    return redirect('deepsort:test')


def view_images(request):
    context = {'videos': 1}

    return render(request, 'deepsort/select_view.html', context)


def check(request):
    context ={
        'videos':1,
    }

    return render(request, 'deepsort/check.html', context)


async def run(request, id):
    return redirect('deepsort:test')


def save_to_database(request):
    context = {'file_path': 1}

    return render(request, 'deepsort/save.html', context)

templates/deepsort/check.html
{% extends 'base.html' %}

{% block title %} | Check {% endblock %}

{% load static %}

{% block content %}

<div class="p-3 text-center">
    <h1>Select Video To Run Deepsort</h1>
    {% for video in videos %}
    <div>
        <a class="h5" href="{{ video.get_absolute_url }}">{{ video.title }}</a>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/deepsort/save.html
{% extends 'base.html' %}

{% block title %} | Select view {% endblock %}

{% load static %}

{% block content %}

<div class="p-3 text-center">
    <h1>Select Video To Save Image</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {% for path in file_path %}
        <div>
            <button type="submit" id="title" name="title" value="{{path}}" class="btn btn-outline-primary" href="{% url 'deepsort:save' %}">{{path}}</button>
        </div>
        {% endfor %}
    </form>
</div>

{% endblock %}

templates/deepsort/select_view.html
{% extends 'base.html' %}

{% block title %} | Select view {% endblock %}

{% load static %}

{% block content %}

<div class="p-3 text-center">
    <h1>Select Video To See People</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {% for video in videos %}
        <div>
            <button type="submit" name="video_id" value="{{video.id}}" class="btn btn-outline-primary" href="{% url 'deepsort:view_images' %}">{{video.title}}</button>
        </div>
        {% endfor %}
    </form>
</div>

{% endblock %}

templates/deepsort/test.html
{% extends 'base.html' %}

{% block title %} | Deepsort {% endblock %}

{% load static %}

{% block content %}

<div class="p-3 text-center">
    <a type="button" class="btn btn-outline-primary p-3" href="{% url 'deepsort:upload' %}">Upload Video</a>
    <a type="button" class="btn btn-outline-primary p-3" href="{% url 'deepsort:check' %}">Run Video</a>
    <a type="button" class="btn btn-outline-primary p-3" href="{% url 'deepsort:view_images' %}">Check Images</a>
    <a type="button" class="btn btn-outline-primary p-3" href="{% url 'deepsort:save' %}">Save Images To Database</a>
</div>

{% endblock %}

templates/deepsort/upload.html
{% extends 'base.html' %}

{% block title %} | Upload {% endblock %}

{% load static %}

{% block content %}

<form action="" method="post" class="p-3 text-center" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success"> Upload New Video </button>
</form>

{% endblock %}

templates/deepsort/view.html
{% extends 'base.html' %}

{% block title %} | View {% endblock %}

{% load static %}

{% load get_item %}
{% load add_number %}

{% block content %}

<div class="h1 p-1" style="text-align:center;">
    We Found {{ total_people }} people in the video.
</div>

{% for idx in image_files %}
    <div class="p-5">
        <a class="h1">Person {{idx}}</a>
        <form action="{% url 'deepsort:modify_images' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="video_id" value="{{ video_id }}">
            <div class="p-3">
                {% for image in image_files|get_item:idx %}
                    <input type="checkbox" name="images" id="{{image.id}}" value="{{image.id}}" />
                    <label for="{{image.id}}"><img src="{{ image.file.url }}" /></label>
                {% endfor %}
            </div>
            <div class="container" style="text-align:center;">
                <div class="row justify-content-center">
                    <select name="image_to" class="form-control col-2">
                        <option selected="true" disabled="disabled">Transfer To</option>
                        {% for person_index in people_indices %}
                            {% if person_index != idx %}
                            <option value="{{ person_index }}" > {{ person_index }} </option>
                            {% endif %}
                        {% endfor %}
                    </select>
                    <input type="submit" name="change" value="change" class="btn btn-primary btn-lg btn-block col-2">
                </div>
                <div class="row justify-content-center">
                    <input type="submit" name="delete" value="delete" class="btn btn-danger btn-lg btn-block col-4">
                </div>
            </div>
        </form>
    </div>
{% endfor %}


{% endblock %}